from puzzle_impls.polyomino import (
    Placement,
    Polyomino,
    all_adjacent_different_shape,
    different_shape_across,
    enumerate_placements,
    no_boundary_cross,
    polyomino,
    same_shape_across,
)
from puzzle_impls.puzzles import (
    HitoriPuzzle,
    NurikabePuzzle,
    ShikakuPuzzle,
    SlitherlinkPuzzle,
    SudokuPuzzle,
    TentsPuzzle,
    TilingPuzzle,
    YajilinPuzzle,
)
from puzzle_impls.regions import (
    Region,
    enumerate_connected_regions,
    enumerate_rectangles,
    filter_number_equals_area,
    filter_one_number_per_region,
    filter_same_number_combination,
)
from puzzle_impls.shikaku import ShikakuRect, enumerate_shikaku_rectangles

__all__ = [
    "HitoriPuzzle",
    "NurikabePuzzle",
    "Placement",
    "Polyomino",
    "Region",
    "ShikakuPuzzle",
    "ShikakuRect",
    "SlitherlinkPuzzle",
    "SudokuPuzzle",
    "TentsPuzzle",
    "TilingPuzzle",
    "YajilinPuzzle",
    "all_adjacent_different_shape",
    "different_shape_across",
    "enumerate_connected_regions",
    "enumerate_placements",
    "enumerate_rectangles",
    "enumerate_shikaku_rectangles",
    "filter_number_equals_area",
    "filter_one_number_per_region",
    "filter_same_number_combination",
    "no_boundary_cross",
    "polyomino",
    "same_shape_across",
]
